apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0         # Maximum number of Pods that can be unavailable during the update
      maxSurge: 2               # Maximum number of Pods that can be created over the desired number of Pods
  template:
    metadata:
      labels:
        app: planet-app
    spec:
      containers:
      - name: planet-app
        image: 122610524382.dkr.ecr.us-east-2.amazonaws.com/student-management-project:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: planet-app-service
spec:
  type: NodePort
  selector:
    app: planet-app
  ports:
  - port: 80
    targetPort: 80

