apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: planet-app
  template:
    metadata:
      labels:
        app: planet-app
    spec:
      containers:
      - name: planet-app
        image: 122610524382.dkr.ecr.us-east-2.amazonaws.com/planet-app:1.0.6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: planet-app-service
spec:
  selector:
    app: planet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
