name: Deploy to planet-app on ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # this is your deployment EC2 runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 400 private_key.pem

    - name: Upload files to temp folder on EC2
      run: |
        scp -i private_key.pem -o StrictHostKeyChecking=no \
        index.php planets.php style.css \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

    - name: Move files to web directory using sudo
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
        "sudo mv /home/${{ secrets.EC2_USER }}/index.php /home/${{ secrets.EC2_USER }}/planets.php /home/${{ secrets.EC2_USER }}/style.css ${{ secrets.EC2_PATH }}/"


    - name: Restart Web Server on EC2 target
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "systemctl daemon-reload" \
          "sudo systemctl restart apache2 || sudo systemctl restart nginx"
